### ISSUE TITLE
Error handling load timeline

### ISSUE THREAD

**Issue by n41r0j** [1dv508-group4/TimeManager#66]
Every file can be loaded, even images. That results in a NullPointerException and the user is not informed.

**Comment by MehdiHmidi523** [comment]
The one taking care of this part forgot to check @AmrMa 's code for example:
   FileChooser.ExtensionFilter extFilterJPG = new FileChooser.ExtensionFilter("JPG files (*.jpg)","*.JPG");

**Comment by AmrMa** [comment]
chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("XML Files (*.xml)", "*.xml"));

**Comment by n41r0j** [comment]
This should also be a test, btw
